#reference here: https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#


#---------------------------------#
#    environment configuration    #
#---------------------------------#
sudo: required
language: ruby
dist: trusty

services:
- docker

addons:
  hosts:
  - webui.io


#---------------------------------#
#       build configuration       #
#---------------------------------#

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

install:
  - docker pull microsoft/aspnetcore-build:1.0-1.1
  - docker pull microsoft/aspnetcore:1.1
  
script:
  - docker-compose -f docker-compose.build.yml -p netcorebuild run ci-build
  - docker-compose -f docker-compose.yml -p webui build
  - docker-compose -f docker-compose.yml -p webui up -d
  - sleep 30
  - docker ps
  - docker logs webui
  - curl http://webui.io:5000